# Generated by Django 4.1.2 on 2023-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='course',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='performance',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='teacher',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
