# Generated by Django 4.1.2 on 2023-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_course_person_performance_person_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='performance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
    ]
