# Generated by Django 4.1.2 on 2023-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_person_course_alter_person_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jour_name_place',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='typ_work',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
    ]
