# Generated by Django 4.1.2 on 2023-03-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_person_jour_name_place_person_typ_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='s_id',
        ),
    ]
